//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramaDivisibilidadCLI {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgramaDivisibilidadCLI.TextoResource", typeof(TextoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base must be an integer greater than one..
        /// </summary>
        public static string ErrorBase {
            get {
                return ResourceManager.GetString("ErrorBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base must be a positive integer greater than one and coprime with the base.
        ///Two numbers are coprime if their greatest common divisor is greater than one..
        /// </summary>
        public static string ErrorBaseCoprima {
            get {
                return ResourceManager.GetString("ErrorBaseCoprima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of coefficients must be a positive integer..
        /// </summary>
        public static string ErrorCoeficientes {
            get {
                return ResourceManager.GetString("ErrorCoeficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The divisor must be a non-negative integer.
        ///Keep in mind that numbers divisible by a negative number are divisible to its absolute value..
        /// </summary>
        public static string ErrorDivisor {
            get {
                return ResourceManager.GetString("ErrorDivisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The divisor, the base and coefficient amount must be positive integers..
        /// </summary>
        public static string ErrorNumerico {
            get {
                return ResourceManager.GetString("ErrorNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The divisor and the base must be coprime, their greatest common divisor must be greater than one..
        /// </summary>
        public static string ErrorPrimo {
            get {
                return ResourceManager.GetString("ErrorPrimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outputs a longer help document explaining this application more in-depth..
        /// </summary>
        public static string HelpAyuda {
            get {
                return ResourceManager.GetString("HelpAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outputs short document with information on how to run this program..
        /// </summary>
        public static string HelpAyudaCorta {
            get {
                return ResourceManager.GetString("HelpAyudaCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reads the divisor, base, and optionally the number of coefficients as arguments, not as dialog input. Must be two or three valid 64-bit integers..
        /// </summary>
        public static string HelpDirecto {
            get {
                return ResourceManager.GetString("HelpDirecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a May return other types of rules, also outputs explanations on how to apply them, ignores all other flags, except -d..
        /// </summary>
        public static string HelpExtendido {
            get {
                return ResourceManager.GetString("HelpExtendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outputs coefficient rule as a JSON object, changes made by other flags are not ignored..
        /// </summary>
        public static string HelpJson {
            get {
                return ResourceManager.GetString("HelpJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gives the coefficient rule a name, which is included in its output..
        /// </summary>
        public static string HelpNombre {
            get {
                return ResourceManager.GetString("HelpNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Used to prevent dialog mode from explicitly asking for binary flags, does not affect output..
        /// </summary>
        public static string HelpSaltar {
            get {
                return ResourceManager.GetString("HelpSaltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outputs all coefficient rules with elements whose absolute value is less than the divisor..
        /// </summary>
        public static string HelpTodos {
            get {
                return ResourceManager.GetString("HelpTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base of the rule: .
        /// </summary>
        public static string MensajeDialogoBase {
            get {
                return ResourceManager.GetString("MensajeDialogoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of coefficients in the rule: .
        /// </summary>
        public static string MensajeDialogoCoeficientes {
            get {
                return ResourceManager.GetString("MensajeDialogoCoeficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor of the rule: .
        /// </summary>
        public static string MensajeDialogoDivisor {
            get {
                return ResourceManager.GetString("MensajeDialogoDivisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to obtain coefficient rules, type a different letter to obtain rules: .
        /// </summary>
        public static string MensajeDialogoExtendido {
            get {
                return ResourceManager.GetString("MensajeDialogoExtendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The program was interrupted..
        /// </summary>
        public static string MensajeDialogoInterrumpido {
            get {
                return ResourceManager.GetString("MensajeDialogoInterrumpido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to output the rule as a JSON, if the rule is not going to be parsed type another letter: .
        /// </summary>
        public static string MensajeDialogoJson {
            get {
                return ResourceManager.GetString("MensajeDialogoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of the rule, can be left empty: .
        /// </summary>
        public static string MensajeDialogoRegla {
            get {
                return ResourceManager.GetString("MensajeDialogoRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to calculate another rule: .
        /// </summary>
        public static string MensajeDialogoRepetir {
            get {
                return ResourceManager.GetString("MensajeDialogoRepetir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtained the following rule: .
        /// </summary>
        public static string MensajeDialogoResultado {
            get {
                return ResourceManager.GetString("MensajeDialogoResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to output all the rules derived from the original, type a different letter to obtain the minimum rule: .
        /// </summary>
        public static string MensajeDialogoTodas {
            get {
                return ResourceManager.GetString("MensajeDialogoTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The rule was calculated..
        /// </summary>
        public static string MensajeFinDirecto {
            get {
                return ResourceManager.GetString("MensajeFinDirecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will be asked to input data throught the console, write {0} to interrupt the program..
        /// </summary>
        public static string MensajeInicioDialogo {
            get {
                return ResourceManager.GetString("MensajeInicioDialogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor: {0}, Base: {1}, Coefficients: {2}..
        /// </summary>
        public static string MensajeParametrosDirecto {
            get {
                return ResourceManager.GetString("MensajeParametrosDirecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit message has been detected, execution was interrupted..
        /// </summary>
        public static string MensajeSalidaVoluntaria {
            get {
                return ResourceManager.GetString("MensajeSalidaVoluntaria", resourceCulture);
            }
        }
    }
}
