//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModosEjecucionInterno.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextoEjecucionInterno {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextoEjecucionInterno() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModosEjecucionInterno.Recursos.TextoEjecucionInterno", typeof(TextoEjecucionInterno).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexpected error ocurred, consider creating a new Issue on GitHub if it isn&apos;t present, include the trace above and the arguments provided:
        ///https://github.com/JosePrietoPaez/CalcDiv/issues.
        /// </summary>
        public static string DialogoExcepcionInesperada {
            get {
                return ResourceManager.GetString("DialogoExcepcionInesperada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base of the rule: .
        /// </summary>
        public static string MensajeDialogoBase {
            get {
                return ResourceManager.GetString("MensajeDialogoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of coefficients in the rule: .
        /// </summary>
        public static string MensajeDialogoCoeficientes {
            get {
                return ResourceManager.GetString("MensajeDialogoCoeficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write a non-negative integer:.
        /// </summary>
        public static string MensajeDialogoDividendoBucle {
            get {
                return ResourceManager.GetString("MensajeDialogoDividendoBucle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number was not valid or negative:.
        /// </summary>
        public static string MensajeDialogoDividendoError {
            get {
                return ResourceManager.GetString("MensajeDialogoDividendoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write all the numbers to apply the rules to, stop by writing &quot;{0}&quot;:.
        /// </summary>
        public static string MensajeDialogoDividendoVacio {
            get {
                return ResourceManager.GetString("MensajeDialogoDividendoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor of the rule: .
        /// </summary>
        public static string MensajeDialogoDivisor {
            get {
                return ResourceManager.GetString("MensajeDialogoDivisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to obtain coefficient rules, type a different letter to obtain rules: .
        /// </summary>
        public static string MensajeDialogoExtendido {
            get {
                return ResourceManager.GetString("MensajeDialogoExtendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The program was interrupted..
        /// </summary>
        public static string MensajeDialogoInterrumpido {
            get {
                return ResourceManager.GetString("MensajeDialogoInterrumpido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to output the rule as a JSON, if the rule is not going to be parsed type another letter: .
        /// </summary>
        public static string MensajeDialogoJson {
            get {
                return ResourceManager.GetString("MensajeDialogoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of the rule, can be left empty: .
        /// </summary>
        public static string MensajeDialogoRegla {
            get {
                return ResourceManager.GetString("MensajeDialogoRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to calculate another rule: .
        /// </summary>
        public static string MensajeDialogoRepetir {
            get {
                return ResourceManager.GetString("MensajeDialogoRepetir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtained the following rule: .
        /// </summary>
        public static string MensajeDialogoResultado {
            get {
                return ResourceManager.GetString("MensajeDialogoResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &quot;s&quot; to output all the rules derived from the original, type a different letter to obtain the minimum rule: .
        /// </summary>
        public static string MensajeDialogoTodas {
            get {
                return ResourceManager.GetString("MensajeDialogoTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The rule was calculated..
        /// </summary>
        public static string MensajeFinDirecto {
            get {
                return ResourceManager.GetString("MensajeFinDirecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will be asked to input data throught the console, write {0} to interrupt the program..
        /// </summary>
        public static string MensajeInicioDialogo {
            get {
                return ResourceManager.GetString("MensajeInicioDialogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit message has been detected, execution was interrupted..
        /// </summary>
        public static string MensajeSalidaVoluntaria {
            get {
                return ResourceManager.GetString("MensajeSalidaVoluntaria", resourceCulture);
            }
        }
    }
}
