//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operaciones.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextoCalculos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextoCalculos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Operaciones.Recursos.TextoCalculos", typeof(TextoCalculos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An integer in base {0} will be divisible by {1} if .
        /// </summary>
        public static string CalculosCrearMensaje {
            get {
                return ResourceManager.GetString("CalculosCrearMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisibility cannot be applied to zero..
        /// </summary>
        public static string CalculosExtendidaMensajeCero {
            get {
                return ResourceManager.GetString("CalculosExtendidaMensajeCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a its first {0} digits are a multiple of .
        /// </summary>
        public static string CalculosExtendidaMensajeCifrasFinal {
            get {
                return ResourceManager.GetString("CalculosExtendidaMensajeCifrasFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  is composed of powers of the prime factors of .
        /// </summary>
        public static string CalculosExtendidaMensajeCifrasPrincipio {
            get {
                return ResourceManager.GetString("CalculosExtendidaMensajeCifrasPrincipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result is too large.
        /// </summary>
        public static string CalculosExtendidaMensajeExceso {
            get {
                return ResourceManager.GetString("CalculosExtendidaMensajeExceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find an alternative rule, apply the coefficient rule if possible..
        /// </summary>
        public static string CalculosExtendidaMensajeFracaso {
            get {
                return ResourceManager.GetString("CalculosExtendidaMensajeFracaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All integers are divisible by one..
        /// </summary>
        public static string CalculosExtendidaMensajeUno {
            get {
                return ResourceManager.GetString("CalculosExtendidaMensajeUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a after separating its digits in groups of {0} beginning at the unit digit, the difference of the sum of the even groups and the odd groups is a multiple of .
        /// </summary>
        public static string CalculosExtendidaRestarFinal {
            get {
                return ResourceManager.GetString("CalculosExtendidaRestarFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  is a divisor of {0} to the power of {1} plus one ({2}).
        /// </summary>
        public static string CalculosExtendidaRestarPrincipio {
            get {
                return ResourceManager.GetString("CalculosExtendidaRestarPrincipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a after separating its digits in groups of {0} beginning at the unit digit, the sum of the groups is a multiple of .
        /// </summary>
        public static string CalculosExtendidaSumarFinal {
            get {
                return ResourceManager.GetString("CalculosExtendidaSumarFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  is a divisor of {0} to the power of {1} minus one ({2}).
        /// </summary>
        public static string CalculosExtendidaSumarPrincipio {
            get {
                return ResourceManager.GetString("CalculosExtendidaSumarPrincipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the difference of the sum of the digits in even positions and the ones in odd positions is a multiple of .
        /// </summary>
        public static string CalculosValorUnoRestarFinal {
            get {
                return ResourceManager.GetString("CalculosValorUnoRestarFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  is a divisor of {0} plus one.
        /// </summary>
        public static string CalculosValorUnoRestarPrincipio {
            get {
                return ResourceManager.GetString("CalculosValorUnoRestarPrincipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the sum of its digits is a multiple of .
        /// </summary>
        public static string CalculosValorUnoSumarFinal {
            get {
                return ResourceManager.GetString("CalculosValorUnoSumarFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  is a divisor of {0} minus one.
        /// </summary>
        public static string CalculosValorUnoSumarPrincipio {
            get {
                return ResourceManager.GetString("CalculosValorUnoSumarPrincipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base must be greater than one.
        /// </summary>
        public static string ReglaBaseMenorError {
            get {
                return ResourceManager.GetString("ReglaBaseMenorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The divisor cannot be negative.
        /// </summary>
        public static string ReglaDivisorNegativoError {
            get {
                return ResourceManager.GetString("ReglaDivisorNegativoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The given rule was empty.
        /// </summary>
        public static string ReglaVaciaError {
            get {
                return ResourceManager.GetString("ReglaVaciaError", resourceCulture);
            }
        }
    }
}
